baseurl = "https://www.ephemeralenvironments.io"
languageCode = "en-us"
title = "PreviewEphemeralEnvironments.io"
theme = "hugo-theme-previewenvironments"

[taxonomies]
  feature = "features"

[params]
  description = "PreviewEnvironments.io"
  ogimage = "/images/previewenvironments.png"
  copyright = "Shipyard Build, Inc."
  edit_link = "https://github.com/previewenvironments/previewenvironments/edit/master/docs/"
  search = true
  contributor ="Shipyard"
  contributorurl = "https://www.shipyard.build"
  image = "/images/preview-environments.png"



[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
